let handler  = async (m, { conn }) => {
conn.reply(m.chat,`*VERDADE*\n*“${pickRandom(global.verdad)}”*\n*(Bem sem graça, o dono não tem criatividade e pegou tudo em um site duvidoso.)*`, m)
}
handler.help = ['verdad']
handler.tags = ['fun']
handler.command = /^verdade/i
export default handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

global.verdad = [
"Você já gostou de alguém? Há quanto tempo?",
"Se possível ou se você quiser, no gc/fora do gc, com quem você vai fazer amizade? (Pode ser diferente/do mesmo tipo)",
"Qual é o seu maior medo?",
"Você já gostou de alguém e sentiu essa pessoa gostar de você também?",
"Qual é o nome do ex-namorado da sua amiga de quem você gostou secretamente?",
"Você já roubou dinheiro da sua mãe ou do seu pai? O motivo?",
"o que te faz feliz quando você está triste",
"Você já teve um amor não correspondido? Se você já esteve com quem? Como se sente mano?",
"Você já teve um caso com alguém?",
"mais temido",
"quem é a pessoa mais influente na sua vida",
"como você está orgulhoso este ano",
"quem é a pessoa que pode te deixar doente",
"quem é a pessoa que já te deu tesão",
"(para os muçulmanos) você nunca rezou o dia todo?",
"Quem está mais próximo do seu tipo ideal de parceiro aqui",
"Com quem você gosta de brincar?",
"Você já rejeitou alguém? Por quê?",
"Mencione o incidente que o magoou e do qual ainda se lembra",
"Que conquistas você obteve este ano?",
"Qual é o seu pior hábito na escola?", 
"Qual programa de TV você mais odeia? Diga que você está certo!", 
"Qual é o vestido mais feio (na sua opinião) que você já usou e quando o usou? ", 
"Qual é a pior coisa (fofoca) que você disse sobre seu amigo?","Qual é a coisa mais embaraçosa sobre você?",
"Qual é a primeira coisa que você vê quando olha para outra pessoa (do oposto sexo)?",
"Qual é a primeira coisa que vem à sua mente quando você se olha no espelho?",
"Qual é a coisa mais idiota que você já fez na vida?","Qual é o pior sonho que você já teve?",
"Qual é o sonho mais louco que você pode se lembrar até agora?",
"Qual é a sua pior característica na sua opinião?",
"Qual característica você gostaria de mudar em você?",
"Que característica você gostaria de mudar em seu amigo?",
"O que você faria se seu namorado lhe dissesse que você tem um nariz ou dedos ruins?",
"Em que você pensa antes de dormir? Ex.: fantasia com um parceiro, etc.",
"O que você acha que mais se destaca em você?", "Qual parte do corpo do seu amigo você mais gosta e gostaria de ter?",
"Qual parte do seu corpo você mais odeia?", "De todas as aulas na escola, em qual você gostaria de entrar e qual você gostaria de evitar?",
"Descreva seu amigo mais próximo!", "Descreva-se em uma palavra!", "Que filmes e músicas fizeram você chorar?",
"O que você manteve em segredo até agora e ninguém descobriu?",
"Qual é a coisa mais romântica que alguém (do sexo oposto) já fez ou deu a você?",
"Qual é a coisa mais desagradável que você já experimentou?",
"Se você nascesse de novo e tivesse que ser um de seus amigos, quem você escolheria ser?",
"Se você tem superpoder/superpoder, o que quer fazer?",
"Se o apocalipse chegar em breve, o que você fará?",
"Se lhe pedissem para fazer uma cirurgia plástica em uma amostra do rosto de seu colega de classe, quem você imitaria?",
"Você já roubou alguma coisa?",
"Você tem medo de morrer? Por quê?",
"Quando foi a última vez que você chorou e por quê?",
"Quais são suas habilidades especiais?",
"Como você pode gostar da pessoa que você gosta?",
"O que você acha que é uma boa característica do seu amigo mais próximo que ele ou ela não conhece?",
"Com que tipo de pessoa você gostaria de se casar um dia?",
"Na sua opinião, qual é o trabalho mais atraente para o amigo sentado ao seu lado? E por quê?",
"Com quem você quer trocar por um dia? (amigos mais próximos que vocês dois conhecem) e por quê",
"Você já esperou secretamente que o relacionamento de alguém com a namorada terminasse? Quem?",
"Você prefere FRIENDS ou FRIENDS? Por quê?",
"Qual frase você mais lembra e gosta?",
"Que segredos você nunca contou aos seus amigos até agora?",
"Quem são seus verdadeiros modelos?",
"Qual dos seus amigos você acha que é a mãe?",
"Qual dos seus amigos você acha que tem menos corte de cabelo?",
"Qual dos seus amigos é o mais fotogênico?",
"Quem é seu melhor ex? E por que eles terminaram ?!",
"Qual é o nome do artista com quem você conversou secretamente?",
"Qual era o nome do professor que você gostava?",
"Qual é o nome da ex-namorada do seu amigo de quem você gostava secretamente?",
"Qual é o nome da pessoa (do sexo oposto) que você acha que seria divertido ser namorada?",
"Qual é o nome da pessoa que você odeia, mas acha que essa pessoa gosta de você (não necessariamente do sexo oposto)?",
"Qual é o nome da pessoa para quem você está apontando secretamente?",
"Quem é a pessoa (do sexo oposto) que mais passa pela sua cabeça?",
"Quem é a pessoa mais chata entre seus amigos? O motivo!",
"Qual dos seus amigos você acha que deveria ser renovado?",
"Quem está mais próximo do seu par ideal aqui?",
"Pai ou mãe",
"A parte do corpo que você não gosta",
"Você já traiu?",
"Você já foi beijado?",
"Qual é a primeira coisa que você faria se acordasse como o sexo oposto?",
"Você já deixou alguém se meter em problemas por algo que você fez?",
"Qual foi a coisa mais embaraçosa que você já fez na vida?",
"Qual é a razão mais ridícula para você terminar com alguém?",
"Qual é o pior hábito que você tem?",
"Qual você acha que é a sua melhor característica? E qual é a sua pior?",
"Qual é a coisa mais corajosa que você já fez?",
"Quando foi a última vez que você fez xixi na cama?",
"O que você mais sonha em dormir?",
"Se você vai ganhar dinheiro ilegalmente, como você faz isso?",
"Que coisas infantis você continua fazendo?",
"Se você fosse cego, quem seria seu cão-guia?",
"O que mais te impressiona?",
"Se você pudesse usar apenas 3 palavras pelo resto da noite a partir de agora, quais seriam?",
"Se você fosse um ditador, qual lei você aprovaria primeiro?",
"Se você vivesse durante a era nazista, quem você seria?",
"Qual foi a experiência mais embaraçosa na escola/tempo de estudo/educação/ano passado?",
"Qual é o maior erro da sua vida?",
"O que você nunca faria, mesmo se soubesse que só tem 12 horas de vida?",
"Que crimes você cometeu?",
"Conte-me um segredo da sua infância.",
"Qual é o seu maior representante (secreto)?",
"O que você quer fazer comigo... (x pessoa), se mais tarde puder apagar a memória dele (dele,...)?",
"Qual é a pior coisa que você já fez para alguém?",
"De quem você gosta mais?",
"Você já se apaixonou por algum dos presentes?",
"Se você fosse um vampiro, qual de nós você morderia agora?",
"Você já defecou em público?",
"Qual é a sua fantasia mais sombria?",
"Qual é a melhor coisa que você já teve com outra pessoa?",
"Qual é o maior desvio para você?",
"O que você mais gosta no seu corpo e o que é mais feio?",
"Quem você gostaria de ver nu?",
"Quem nesta rodada pode fazer você se apaixonar?",
"Você já teve um sonho erótico onde alguém desse grupo aconteceu?",
"Se você for fazer uma tatuagem na região genital, o que vai ter aí?",
"O que é mais importante em um relacionamento: sexo ou amor?",
"Você acha que sexo é legal, bem, bem, divertido às vezes, ou você realmente não se importa?",
"O que te faz amar de verdade?",
"Quantas vezes por semana/mês você faz sexo e com que frequência você quer fazer sexo?",
"Com quantos parceiros sexuais você dormiu?",
"Que parte do corpo te deixa mais bonita?",
"Como, onde e com quem você esteve primeiro?",
"Quão importante são as preliminares prolongadas para você?",
"O que um homem ou uma mulher deve fazer para seduzi-lo?",
"Você já fez sexo com um bom amigo?",
"Você já fez sexo com algum desses grupos, exceto com seu parceiro?",
"Qual animal combina mais com você e por quê?",
"Qual é o seu pior encontro?",
"Quem você quer beijar agora?",
"Qual é a sua fantasia secreta obscura?",
"Você prefere tatuar sua bunda ou colocar um piercing na língua?",
"Você é sempre leal?",
"Você tem uma paixão adolescente?",
"Por quem você se apaixonou?",
"Qual celebridade você gostaria de namorar?",
"Qual foi o momento mais embaraçoso da sua vida?",
"Qual boca você mais gosta no grupo aqui?",
"Qual jogador tem a mão mais bonita?",
"Onde foi seu primeiro beijo?",
"Quem do grupo você mais gostaria de beijar?",
"Quem à mesa é talvez o mais engraçado?",
"Qual é o maior erro da sua vida?",
"Algo embaraçoso aconteceu com você em um encontro?",
"Você já teve contato com drogas?",
"Qual pessoa você quer beijar agora?",
"Quando foi a última vez que você ficou bêbado?",
"Você já colou em um teste da escola?",
"Você já roubou alguma coisa no passado?",
"Você ronca à noite?",
" Qual é a tua canção favorita?",
"Com quais jogadores você negociará por 1 semana e por quê?",
"Você se mudou para uma ilha deserta, quem você tirou daqui?",
"Do que você mais tem medo?",
"Onde você faz a barba em todos os lugares?",
"Você tem um apelido?",
"Você olha no banheiro antes de se lavar?",
"Quem te deu o pior desgosto?",
"Quantas vezes você já beijou",
"Qual é a coisa mais embaraçosa que já aconteceu com você?",
"Quantos meninos/meninas você já beijou?",
"Por quem você está apaixonado?",
"Que estrela você gosta",
"Você começou algo com alguém atualmente?",
"Você já roubou alguma coisa?"
] 
